### ISSUE TITLE
Как активный искатель я могу в чате задать фильтры поиска и получить сообщение с первым найденным пользователем

### ISSUE THREAD

**Issue by Oleg-Stukalov** [Oleg-Stukalov/ADPY-14_project_8_VK_bot#1]
- [ ] Работает фильтр: пол #2 
- [ ] Работает фильтр: возраст #3
- [ ] Работает фильтр: город #4
- [ ] Работает фильтр: семейное положение #5 
- [ ] Работает вариант не фильтровать по параметру #6
- [ ] После запуска фильтрации находятся результаты #7
- [ ] Список результатов сохраняется в памяти для этого пользователя #8
- [ ] Из списка результатов исключаются уже показанные #9
- [ ] Из списка результатов показываем одного и запоминаем кого показали #10
- [ ] Показываем пользователя указав его имя, фамилию, возраст, город и 3 фото   #11
- [ ] Если пользователь понравился пишу: да, тогда пользователь сохраняется в таблице с признаком "лайк" #12
- [ ] *Если понравился пользователь то, предлагаем отправить СМС или оплатить через ВК и получить прямые контакты 
- [ ] Для каждого пользователя мы храним его состояние #13
